DMS_trips/config/routes.rb
Rails.application.routes.draw do

  root 'staticpages#home'

  get 'filtros' => 'staticpages#json'

  get 'paris' => 'staticpages#paris'

  get 'madrid' => 'staticpages#madrid'

  get 'under_construction' => 'staticpages#under_construction'

  get 'summary/print_error' => 'staticpages#print_error'

  get 'summary' =>'flights#show'

  post 'summary' => 'flights#index'

  get 'summary' => 'flights#index'

  get 'summary/choice' => 'flights#choice'

  post 'summary/choice' => 'flights#choice'

end

DMS_trips/app/models/flight.rb
class Flight < ActiveRecord::Base


	def self.search(origin,destination,fechaida)


		#The result of the search has to be all the flights that have the origin and destinations entered by user

		where("origin like ?", "%#{origin}%").where("destination like ?", "%#{destination}%").where("from_date like ?", "%#{fechaida}%")



		#where(origin: origin).where(destination: destination)

		#@@origen.each do |flight|
			#if flight.destination == destination
				#@flights.push flight
				#@flights.each do |flight_found|
					#@result = "#{flight_found.origin},#{flight_found.destination},#{flight_found.price}"   
				#end
			#else @no_flight = "No flights found for your search."
			#end
		#end

		#Flight.where(origin: origin).where(destination: destination)
		
	end

	def self.search_cheaper_flight
	arrprice= []
	flights_prices = Flight.where(origin: 'Madrid').where(countrydestination: 'Francia')
	flights_prices.each do |flight|
		arrprice << flight.price 
	end
	
	 Flight.find_by_price(arrprice.min)

	end


	def searchflights
		





		@flights = Flight.all
		ActiveRecord::Base.include_root_in_json = true
		@flightsall=@flights.to_json
	end
end

DMS_trips/app/models/result.rb
class Result < ActiveRecord::Base
end

DMS_trips/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

DMS_trips/app/controllers/flights_controller.rb
class FlightsController < ApplicationController

	def index
		render 'index'
	end
	
	def show
		#Searching departure flights
		if params[:origin] && params[:destination] && params[:from_date]
		@a = params[:from_date].map{|key,value| value}
		@date=Date.new(@a[0].to_i,@a[1].to_i,@a[2].to_i)

		@flights = Flight.search(params[:origin], params[:destination], @date )

		#Searching flights back
		@b = params[:to_date].map{|key,value| value}
		@to_date=Date.new(@b[0].to_i,@b[1].to_i,@b[2].to_i)

		@flights_back = Flight.search(params[:destination], params[:origin], @to_date)

		#@date = [params[:from_date][:year], params[:from_date][:month], params[:from_date][:day]]
		#else
		#redirect_to action: 'index', controller: 'flights'
		#flash[:error] = "This location doesn't exist!"
		end
		
		render 'show', :layout=>'applicationsummary'



		# @origin = search_params[:origin]
		# @destination = search_params[:destination]
		# @flights = Flight.search(@origin, @destination)
		# puts @flights
  	# 	if params[:origin] && params[:destination]

 		# 	 @flights = Flight.search(params[:origin], params[:destination])


 		
 	end

 	def choice
		render 'choice', layout: 'applicationchoice'
	end

    #private
	# def search_params
	# 	params.permit(:origin, :destination)
	# end




end

#(:all, :conditions => ['name LIKE ?', "%#{params[:origin]}%"], :conditions => ['name LIKE ?', "%#{params[:destination]}%"] )

DMS_trips/app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
	def json
		@flights=Flight.all
		@flights.to_json
		render json: @flights

	end
	def home

		@flight_minor_price = Flight.search_cheaper_flight
		render 'home', :layout=>'applicationhome'
	end

	def paris
		render 'paris', :layout=>'applicationparis'
	end

	def madrid
		render 'madrid', :layout=>'applicationmadrid'
	end

	def under_construction
		render 'under_construction', :layout=>'applicationunder_construction'
	end

	def print_error
		render 'print_error'
	end

end

DMS_trips/app/helpers/application_helper.rb
module ApplicationHelper
end

DMS_trips/app/helpers/flights_helper.rb
module FlightsHelper
end

DMS_trips/app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

DMS_trips/app/views/flights/choice.html.erb
<header>

	Hola

</header>

DMS_trips/app/views/flights/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<link rel="stylesheet" type="text/css" href="./css/reset.css" />
	<link rel="stylesheet" type="text/css" href="./css/summarycss.css" />
	<script type="text/javascript" src="./JavaScript/jquery-2.1.1.min.js"></script>
	<!--<script defer type="text/javascript" src="../JavaScript/dataBase_funcionalities.js"></script>-->
	<script type="text/javascript" src="./JavaScript/datos_en_summary.js"></script>
</head>
<body>
	<header>
		<img src="./images/Mapas/logo150.png">
	</header>
	<section class="resumen">
		<span class="span_origen">MADRID</span>
		<span class="span_pais_origen">ESPAÑA</span>
		<span class="span_destino">PARÍS</span>
		<span class="span_pais_destino">FRANCIA</span>
	</section>
	<ul id="lista_resumen_vuelos">
		<li>
			<table class="table_vuelos">
				<tr>
					<th class="ciudad_origen display_inline_block">
						Origen
					</th>
					<th class="ciudad_destino display_inline_block">
						Destino
					</th>
					<th class="fecha_vuelo_salida display_inline_block">
						Fecha Salida
					</th>
					<th class="hora_vuelo_salida display_inline_block">
						Hora Salida
					</th>
					<th class="fecha_vuelo_llegada display_inline_block">
						Fecha Llegada
					</th>
					<th class="hora_vuelo_llegada display_inline_block">
						Hora Llegada
					</th>
					<th class="duracion display_inline_block">
						Duración
					</th>
					<th class="aerolinea display_inline_block">
						Aerolínea
					</th>
				</tr>

				<tr class="vuelo_resumen display_inline_block">
					<td class="ciudad_origen display_inline_block">
						Madrid
					</td>
					<td class="ciudad_destino display_inline_block">
						Paris
					</td>
					<td class="fecha_vuelo_salida display_inline_block">
						06 Nov
					</td>
					<td class="hora_vuelo_salida display_inline_block">
						14:30
					</td>
					<td class="fecha_vuelo_llegada display_inline_block">
						06 Nov
					</td>
					<td class="hora_vuelo_llegada display_inline_block">
						16:30
					</td>
					<td class="duracion display_inline_block">
						02h 00m 
					</td>
					<td class="aerolinea display_inline_block">
						DMS Trips
					</td>
				</tr>

				<tr class="vuelo_resumen display_inline_block">
					<td class="ciudad_origen display_inline_block">
						Paris
					</td>
					<td class="ciudad_destino display_inline_block">
						Madrid
					</td>
					<td class="fecha_vuelo_salida display_inline_block">
						09 Nov
					</td>
					<td class="hora_vuelo_salida display_inline_block">
						14:30
					</td>
					<td class="fecha_vuelo_llegada display_inline_block">
						09 Nov
					</td>
					<td class="hora_vuelo_llegada display_inline_block">
						16:30
					</td>
					<td class="duracion display_inline_block">
						02h 00m 
					</td>
					<td class="aerolinea display_inline_block">
						DMS Trips
					</td>
				</tr>
			</table>
			
		</li>
		
	</ul>
	<table class="tableprecio">
			<tr>
				<td class="tdprecio">
					Precio
				</td>
			</tr>
			<tr>
				<td class="tdpreciocantidad">
					300 €
				</td>
			</tr>
	</table>
	<div class="boton_reservar">
		<a href="" class="reservar">Reservar</a>
	</div>
	
	
</body>
</html>

DMS_trips/app/views/flights/show.html.erb
<header id="header">
		<%= image_tag "logo150.png" %>
	</header>

	<h1 id="title" class="title">Search results:</h1>
	<ul class="ul" id="lista_resumen_vuelos">

		<% @price=[] %>

		<% @flights.each do |flight| %>
			<% @flights_back.each do |flight_back| %>

		<li>

			<table class="table_vuelos">
				<tr>
					<th class="ciudad_origen display_inline_block">
						Origin
					</th>
					<th class="ciudad_destino display_inline_block">
						Destination
					</th>
					<th class="fecha_vuelo_salida display_inline_block">
						Departure date
					</th>
					<th class="hora_vuelo_salida display_inline_block">
						Departure time
					</th>
					<th class="fecha_vuelo_llegada display_inline_block">
						Arrival date
					</th>
					<th class="hora_vuelo_llegada display_inline_block">
						Arrival time
					</th>
					<th class="duracion display_inline_block">
						Duration
					</th>
					<th class="aerolinea display_inline_block">
						Airline
					</th>
					<th class="aerolinea display_inline_block">
						Price
					</th>
					<th>
					</th>
				</tr>

				<tr class="vuelo_resumen display_inline_block">
					
					<td class="ciudad_origen display_inline_block">
						<%= flight.origin %>
						
					</td>
					<td class="ciudad_destino display_inline_block">
						<%= flight.destination %>
						
					</td>
					<td class="fecha_vuelo_salida display_inline_block">
							<%= flight.from_date.to_s %>
						
					</td>
					<td class="hora_vuelo_salida display_inline_block">
							<%= flight.time_departure.to_s %>
						
						
					</td>
					<td class="fecha_vuelo_llegada display_inline_block">
							<%= flight.from_date.to_s %>
					
					</td>
					<td class="hora_vuelo_llegada display_inline_block">
							<%= flight.time_arrive.to_s %>
					
					</td>
					<td class="duracion display_inline_block">
							<%= flight.duracion.to_s + "horas" %>
						
					</td>
					<td class="aerolinea display_inline_block">
							<%= flight.aerolinea %>
					</td>
					<td class="calculateprice display_inline_block">
							$<%= flight.price %>
					</td>
					<td>
						<% p_departure = flight.price %>
						<% p_return = flight_back.price %>
						$<%= p_departure + p_return %>
					</td>
				</tr>
				<tr class="vuelo_resumen display_inline_block">
					<td class="ciudad_origen display_inline_block">
						<%= flight_back.origin %>
						
					</td>
					<td class="ciudad_destino display_inline_block">
						<%= flight_back.destination %>
						
					</td>
					<td class="fecha_vuelo_salida display_inline_block">
							<%= flight_back.from_date.to_s %>
						
					</td>
					<td class="hora_vuelo_salida display_inline_block">
							<%= flight_back.time_departure.to_s %>
						
						
					</td>
					<td class="fecha_vuelo_llegada display_inline_block">
							<%= flight_back.from_date.to_s %>
					
					</td>
					<td class="hora_vuelo_llegada display_inline_block">
							<%= flight_back.time_arrive.to_s %>
					
					</td>
					<td class="duracion display_inline_block">
							<%= flight_back.duracion.to_s + "horas" %>
						
					</td>
					<td class="aerolinea display_inline_block">
							<%= flight_back.aerolinea %>
					</td>
					<td class="calculateprice display_inline_block">
							$<%= flight_back.price %>
					</td>
					<td>
						<input type="submit" value="Book!">

					</td>


				  </tr>
			  	</table>

			</li>
		  <%end%>
		<%end%>
	</ul>
	
	

DMS_trips/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DMSTrips</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

DMS_trips/app/views/layouts/applicationchoice.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DMSTrips</title>
  <%= stylesheet_link_tag    'applicationchoice', media: 'all' %>
  <%= javascript_include_tag 'applicationchoice' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

DMS_trips/app/views/layouts/applicationhome.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DMSTrips</title>
  <%= stylesheet_link_tag    'applicationhome', media: 'all' %>
  <%= javascript_include_tag 'applicationhome' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

DMS_trips/app/views/layouts/applicationmadrid.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DMSTrips</title>
  <%= stylesheet_link_tag    'applicationmadrid', media: 'all' %>
  <%= javascript_include_tag 'applicationmadrid' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

DMS_trips/app/views/layouts/applicationparis.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DMSTrips</title>
  <%= stylesheet_link_tag    'applicationparis', media: 'all' %>
  <%= javascript_include_tag 'applicationparis' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

DMS_trips/app/views/layouts/applicationsummary.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DMSTrips</title>
  <%= stylesheet_link_tag    'applicationsummary', media: 'all' %>
  <%= javascript_include_tag 'applicationsummary' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

DMS_trips/app/views/layouts/applicationunder_construction.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DMSTrips</title>
  <%= stylesheet_link_tag    'applicationunder_construction', media: 'all' %>
  <%= javascript_include_tag 'applicationunder_construction' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

DMS_trips/app/views/staticpages/home.html.erb
	<header>

		<div class="logIn">
			<p class="e-mail-text">E-mail:</p>
			<input type="e-mail" class="logIn-input">
			<p class="password-text">Password:</p>
			<input type="text" class="password-input">
			<a href="" class="signUp-btn">Sign Up</a>
			<button type="submit" class="logIn-btn">Log In</button>
		</div>

		<%= image_tag "logodms200.png", class: "logo" %>



	</header>


		<ul id="menu">

   			<li id="cost">
   				<p class="categories">Cost</p>
    			<ul>
    				<li><input type="checkbox" name="checkbox" id="checkbox_lowcost" value="value"><p class="textfilters">Low Cost</p></li>
    				<li><input type="checkbox" name="checkbox" id="checkbox_mediumcost" value="value"><p class="textfilters">Medium Cost</p></li>
    				<li><input type="checkbox" name="checkbox" id="checkbox_highcost" value="value"><p class="textfilters">High Cost</p></li>
    			</ul>
    		</li>

    		<li id="theme">
    			<p class="categories">Theme</p>
    		    <ul>
    				<li><input type="checkbox" name="checkbox" id="checkbox_id" value="value"><p class="textfilters">Adventure</p></li>
    				<li><input type="checkbox" name="checkbox" id="checkbox_id" value="value"><p class="textfilters">Sun & Beach</p></li>
    				<li><input type="checkbox" name="checkbox" id="checkbox_id" value="value"><p class="textfilters">Snow</p></li>
    				<li><input type="checkbox" name="checkbox" id="checkbox_id" value="value"><p class="textfilters">Relax</p></li>
    			</ul>
    		</li>

    	</ul>
		<div class="menuDec"></div> 

		
		



<!-- ********************************************************************** -->

<!-- OUR FORM TO SEARCH FLIGHTS -->


		<!-- <form action='/summary' method="GET" id="allForm" class="form"> -->
		<%= form_tag summary_path, id: "allForm", class: "form", :method => 'get' do %>
			<input id="roundTrip-btn" class="input round-btn" name="radiobutton" type="radio" checked="checked"><span>Round trip</span>
			<input id="oneWay-btn" class="input round-btn" name="radiobutton" type="radio"><span>One way</span><br>
			<div id="divInputs" class="divInputs">
				<div class="origin_tag tag">
				<%= label_tag(:origin) %>
				<%= text_field_tag (:origin), params[:origin], id: "origin-input" %>
				</div>
				<!-- <input id="origin-input" class="input inputText" type="text" placeholder="Origin"> -->
				<div class="tag">
				<%= label_tag(:from_date) %>
				<%= date_select(:from_date, default: Date.today) %>
				</div>
				<!-- <input id="origin-date" class="input inputDate" type="date"><br> -->
				<div class="destination_tag tag">
				<%= label_tag(:destination) %>
				<%= text_field_tag (:destination), params[:destination], id: "dest-input", class: "input inputText" %>
				</div>
				<!-- <input id="dest-input" class="input inputText" type="text" placeholder="Destination"> -->
				<div class="date_round_trip tag ">
				<%= label_tag(:to_date) %>
				<%= date_select(:to_date, default: Date.today) %>
				</div>
				<!-- <input id="dest-date" class="input inputDate" type="date"><br> -->
				<div>
				<%= button_tag "Add Destination", id:"addDest-btn", class:"addDest-btn", type:"button"%>
				<%= button_tag "Remove Destination", id:"remDest-btn", class:"remDest-btn", type:"button"%><br>
				</div>	
			</div>
			
			<!-- <button id="remDest-btn" class="input remDest-btn">Remove destination</button><br> -->
			<span>Passengers</span>
			<select>
					<option value="1" selected="selected">1</option>
					<option value="2">2</option>
					<option value="3">3</option>
			</select>
				<%= submit_tag "Search", id: "go-btn", :name => nil %>
				<!-- <button action='submit' id="go-btn">GO!</button> -->
			<% end %>
		
	


	<section class="bd ilblock">


<!-- ******************************************************** -->

		<%= image_tag "mapadelmundo.svg.png", id:"mapamundo" %>
		<%= image_tag "spain36default.png", class: "spain" %>
		<%= image_tag "spain36green.png", class: "spaingreen display" %>
		<%= image_tag "spain36yellow.png", class: "spainyellow display" %>
		<%= image_tag "spain36red.png", class: "spainred display" %>
		<%= image_tag "portugal18default.png", class: "portugal" %>
		<%= image_tag "portugal18green.png", class: "portugalgreen display" %>
		<%= image_tag "portugal18yellow.png", class: "portugalyellow display" %>
		<%= image_tag "portugal18red.png", class: "portugalred display" %>
		<%= image_tag "francia31default.png", class: "francia" %>
		<%= image_tag "francia31green.png", class: "franciagreen display" %>
		<%= image_tag "francia31yellow.png", class: "franciayellow display" %>
		<%= image_tag "francia31red.png", class: "franciared display" %>
		<%= image_tag "unitedkingdom34default.png", class: "unitedkingdom" %>
		<%= image_tag "unitedkingdom34green.png", class: "unitedkingdomgreen display" %>
		<%= image_tag "unitedkingdom34yellow.png", class: "unitedkingdomyellow display" %>
		<%= image_tag "unitedkingdom34red.png", class: "unitedkingdomred display" %>
		<%= image_tag "italia36default.png", class: "italia" %>
		<%= image_tag "italia36green.png", class: "italiagreen display" %>
		<%= image_tag "italia36yellow.png", class: "italiayellow display" %>
		<%= image_tag "italia36red.png", class: "italiared display" %>
		<%= image_tag "alemania25default.png", class: "alemania" %>
		<%= image_tag "alemania25green.png", class: "alemaniagreen display" %>
		<%= image_tag "alemania25yellow.png", class: "alemaniayellow display" %>
		<%= image_tag "alemania25red.png", class: "alemaniared display" %>
		<%= image_tag "holanda10default.png", class: "holanda" %>
		<%= image_tag "holanda10green.png", class: "holandagreen display" %>
		<%= image_tag "holanda10yellow.png", class: "holandayellow display" %>
		<%= image_tag "holanda10red.png", class: "holandared display" %>
		<%= image_tag "turquia44default.png", class: "turquia" %>
		<%= image_tag "turquia44green.png", class: "turquiagreen display" %>
		<%= image_tag "turquia44yellow.png", class: "turquiayellow display" %>
		<%= image_tag "turquia44red.png", class: "turquiared display" %>
		<%= image_tag "india90default.png", class: "india" %>
		<%= image_tag "india90green.png", class: "indiagreen display" %>
		<%= image_tag "india90yellow.png", class: "indiayellow display" %>
		<%= image_tag "india90red.png", class: "indiared display" %>
		<%= image_tag "china140default.png", class: "china" %>
		<%= image_tag "china140green.png", class: "chinagreen display" %>
		<%= image_tag "china140yellow.png", class: "chinayellow display" %>
		<%= image_tag "china140red.png", class: "chinared display" %>
		<%= image_tag "australia120default.png", class: "australia" %>
		<%= image_tag "australia120green.png", class: "australiagreen display" %>
		<%= image_tag "australia120yellow.png", class: "australiayellow display" %>
		<%= image_tag "australia120red.png", class: "australiared display" %>
		<%= image_tag "eeuu135default.png", class: "eeuu" %>
		<%= image_tag "eeuu135green.png", class: "eeuugreen display" %>
		<%= image_tag "eeuu135yellow.png", class: "eeuuyellow display" %>
		<%= image_tag "eeuu135red.png", class: "eeuured display" %>
		<%= image_tag "mexico75default.png", class: "mexico" %>
		<%= image_tag "mexico75green.png", class: "mexicogreen display" %>
		<%= image_tag "mexico75yellow.png", class: "mexicoyellow display" %>
		<%= image_tag "mexico75red.png", class: "mexicored display" %>

	</section>
</div>

<!-- ******************************************************** -->

<!-- HOVER´S -->

	<!-- France -->
	<div class="franceDiv">
		<h3 class="francetitle">France</h3>
		<div class="citiesFranceOne">
			<ul class="ulOne">
				<li class="cityLinks"><button id="butParis" class="addBut">Add</button><a href="/paris">Paris</a></li>
				<li class="cityLinks"><button id="butTropez" class="addBut">Add</button><a href="/under_construction">S.Tropez</a></li>
				
			</ul>
		</div>
		<div class="citiesFranceTwo">
			<ul class="ulTwo">
				<li class="cityLinks"><button id="butMarsella" class="addBut">Add</button><a href="/under_construction">Marsella</a></li>
				<li class="cityLinks"><button id="butNiza" class="addBut">Add</button><a href="/under_construction">Niza</a></li>
			</ul>
		</div>
		<div class="offerflight flighthidden">
					<%= "Fly to " + @flight_minor_price.destination + " for " + @flight_minor_price.price.to_s + " euros " %>
		</div>
	</div>

	<!-- Spain -->
	<div class="spainDiv">
		<h3 class="spaintitle">Spain</h3>
		<div class="citiesSpainOne">
			<ul class="ulOne">
				<li class="cityLinks"><button id="butMadrid" class="addBut">Add</button><a href="/madrid">Madrid</a></li>
				<li class="cityLinks"><button id="butBarcelone" class="addBut">Add</button><a href="/under_construction">Barcelone</a></li>
				<li class="cityLinks"><button id="butValence" class="addBut">Add</button><a href="/under_construction">Valence</a></li>
				<li class="cityLinks"><button id="butAlicante" class="addBut">Add</button><a href="/under_construction">Alicante</a></li>
							</ul>
		</div>
		<div class="citiesSpainTwo">
			<ul class="ulTwo">
				<li class="cityLinks"><button id="butSevilla" class="addBut">Add</button><a href="/under_construction">Sevilla</a></li>
				<li class="cityLinks"><button id="butMalaga" class="addBut">Add</button><a href="/under_construction">Malaga</a></li>
				<li class="cityLinks"><button id="butBilbao" class="addBut">Add</button><a href="/under_construction">Bilbao</a></li>
			</ul>
		</div>
	</div>

<!-- ******************************************************** -->
<script>
document.getElementById('checkbox_lowcost').addEventListener("change", getdata);
document.getElementById('checkbox_mediumcost').addEventListener("change", getdata);
document.getElementById('checkbox_highcost').addEventListener("change", getdata);
    </script>
<!--<footer>
	<ol class="footerListOne">
		<li class="hLinks">Follow us:</li>
		<li><a href="">Facebook</a></li>
		<li><a href="">Twitter</a></li>
		<li><a href="">Email us</a></li>
	</ol>
	<ol class="footerListTwo">
		<li class="hLinks">Who are we?</li>
		<li><a href="">DMS Trips</a></li>
		<li><a href="">The Team</a></li>
		<li><a href="">The History</a></li>
	</ol>
	<ol class="footerListThree">
		<li class="hLinks">Patterns:</li>
		<li><a href="">McKinsey Social Iniciative</a></li>
		<li><a href="">Generation Spain</a></li>
		<li><a href="">Ironhack</a></li>
		<li><a href="">ISDI</a></li>
	</ol>
	<%= image_tag "ironhackicon.png", class: "imgFooter", style: "width:90px; height: 50px" %>
	<%= image_tag "generation.png", class: "imgFooter", style: "width:110px; height: 50px" %>
	<%= image_tag "isdi.png", class: "imgFooter", style: "width:160px; height: 50px" %>
	<%= image_tag "mckinsey.jpg", class: "imgFooter", style: "width:70px; height: 70px" %>
</footer>
 -->
 <%= javascript_include_tag :applicationhome -%>s

DMS_trips/app/views/staticpages/print_error.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>ERROR</title>
</head>
<body>
	<h2 style="text-align:center;margin-top:100px">Make sure your printer is connected and installed correctly!</h2>
	<img src="/assets/printer_broken.png" style="display:block;margin:auto">
</body>
</html>

DMS_trips/app/views/staticpages/under_construction.html.erb
<header>

	<div class="logIn">
		<p class="e-mail-text">E-mail:</p>
		<input type="e-mail" class="logIn-input">
		<p class="password-text">Password:</p>
		<input type="text" class="password-input">
		<a href="" class="signUp-btn">Sign Up</a>
		<button type="submit" class="logIn-btn">Log In</button>
	</div>

	<%= image_tag "logodms200.png", class: "logo" %>



</header>

<h1 class="title">City under construction</h1>

<%= image_tag "grua.jpg", class:"grua" %>